// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microservices.product_services.Models;

#nullable disable

namespace Microservices.product_services.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("product_services.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thuốc bột uống",
                            Img = "https://hanvet.com.vn/vn/uploads/HASP/hanmocla%20wsp.jpg",
                            Name = "Hanmocla WSP",
                            Price = 120000.0,
                            Type = "Thuốc Kháng Sinh"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Chuyên trị bệnh đường hô hấp, tiêu hóa.",
                            Img = "https://hanvet.com.vn/vn/uploads/HASP/tylocoli%2020.jpg",
                            Name = "Tylocoli",
                            Price = 120000.0,
                            Type = "Thuốc Kháng Sinh"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kháng sinh đặc hiệu nhất chữa CRD, suyễn, hồng lỵ.",
                            Img = "https://hanvet.com.vn/vn/uploads/HASP/tiamulin%20100%20g.jpg",
                            Name = "TIAMULIN 10%",
                            Price = 120000.0,
                            Type = "Thuốc Kháng Sinh"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Dung dịch nhỏ tai",
                            Img = "https://hanvet.com.vn/uploads/S%E1%BA%A3n%20ph%E1%BA%A9m/S%E1%BA%A3n%20ph%E1%BA%A9m%20cho%20ch%C3%B3%20m%C3%A8o/Han-Otic.JPG",
                            Name = "HAN-OTIC",
                            Price = 120000.0,
                            Type = "Thuốc Ký Sinh Trùng"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Thuốc dùng ngoài chuyên dùng đặc trị nội và ngoại ký sinh trùng",
                            Img = "https://www.google.com/imgres?imgurl=http%3A%2F%2Fhanvet.com.vn%2Fvn%2Fuploads%2FHASP%2Fhanmectin-100.jpg&tbnid=us3FuGXTh7WcEM&vet=12ahUKEwif5tv41YaFAxWGka8BHYRQCusQMygBegQIARAx..i&imgrefurl=https%3A%2F%2Fhanvet.com.vn%2Fvn%2Fscripts%2FprodView.asp%3Fidproduct%3D234%26title%3D-page.html&docid=ysCc1Fnu-Wv3kM&w=2344&h=1968&q=H%C3%ACnh%20%E1%BA%A3nh%20Hanmectin%20Pour-on%20hanvet.com&ved=2ahUKEwif5tv41YaFAxWGka8BHYRQCusQMygBegQIARAx",
                            Name = "Hanmectin Pour-on",
                            Price = 120000.0,
                            Type = "Thuốc Ký Sinh Trùng"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Dung dịch nhỏ giọt điểm da. Diệt ngoại ký sinh trùng",
                            Img = "https://hanvet.com.vn/uploads/S%E1%BA%A3n%20ph%E1%BA%A9m/S%E1%BA%A3n%20ph%E1%BA%A9m%20cho%20ch%C3%B3%20m%C3%A8o/Hanfip-on%20Plus.jpg",
                            Name = "Hanfip-on Plus",
                            Price = 120000.0,
                            Type = "Thuốc Ký Sinh Trùng"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vắc xin nhược độc phòng bệnh Liên cầu khuẩn gây ra ở lợn",
                            Img = "https://hanvet.com.vn/uploads/S%E1%BA%A3n%20ph%E1%BA%A9m/v%E1%BA%AFc%20xin/Gia%20s%C3%BAc/anh%20sp%20Vacxin%20lien%20cau%20LON%20DONG%20KHO.png",
                            Name = "VẮC XIN LIÊN CẦU LỢN",
                            Price = 120000.0,
                            Type = "Vắc Xin"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Vắc xin nhược độc phòng 3 bệnh Tụ huyết trùng, Đóng dấu lợn và Dịch tả lợn",
                            Img = "https://hanvet.com.vn/uploads/S%E1%BA%A3n%20ph%E1%BA%A9m/v%E1%BA%AFc%20xin/Gia%20s%C3%BAc/tam%20li%C3%AAn.png",
                            Name = "VẮC XIN TỤ-DẤU-DỊCH TẢ LỢN",
                            Price = 120000.0,
                            Type = "Vắc Xin"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Vắc xin nhược độc phòng bệnh Giả dại cho lợn",
                            Img = "https://hanvet.com.vn/uploads/S%E1%BA%A3n%20ph%E1%BA%A9m/v%E1%BA%AFc%20xin/Gia%20s%C3%BAc/gia%20dai.png",
                            Name = "VẮC XIN GIẢ DẠI",
                            Price = 120000.0,
                            Type = "Vắc Xin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
