// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Microservices.UserServices.Models;

#nullable disable

namespace Microservices.UserServices.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UserServices.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("UserServices.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Address = "Da Lat",
                            Name = "Admin",
                            PasswordHash = "Uu2FV9A03SzmTmsSK9fO23JoPAKYzlT3C2FnZTl9am0=",
                            PasswordSalt = "gQ7MxCcdwvT5/5Y2GjmHTg==",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            Address = "Da Lat",
                            Name = "Manager",
                            PasswordHash = "B9niwJgKEYL+wTAU0L2Ixl2TzYn6gL3yJvf0WZ3ba8E=",
                            PasswordSalt = "PHVisrRh6CgpNITURfbqAg==",
                            Username = "manager"
                        },
                        new
                        {
                            UserId = 3,
                            Address = "Da Lat",
                            Name = "User",
                            PasswordHash = "1yCt+eTOrurrpw9F5DaivQqeGltj31IWmj5h5C+GUAo=",
                            PasswordSalt = "QV9JAbYyy+Jhmx3RZTd16g==",
                            Username = "user"
                        });
                });

            modelBuilder.Entity("UserServices.Models.UserRole", b =>
                {
                    b.Property<int>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserRoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserRoleId = 1,
                            RoleId = 1,
                            Username = "Admin"
                        },
                        new
                        {
                            UserRoleId = 2,
                            RoleId = 2,
                            Username = "Manager"
                        },
                        new
                        {
                            UserRoleId = 3,
                            RoleId = 3,
                            Username = "User"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
